Add missing locking around I/O operation in startup_byt.c (#11051)
Fixes the following:

../runtime/ocamlrun ../boot/ocamlc -use-prims ../runtime/primitives -strict-sequence -absname -w +a-4-9-41-42-44-45-48-70 -g -warn-error +A -bin-annot -nostdlib -principal -safe-string -strict-formats  -nopervasives -c camlinternalFormatBasics.mli
Fatal error: Fatal error during unlock: Operation not permitted

Similar locking was added to OCaml 4 in commit e6788850078974de6fc5eaee70fe463d24d953db .