Improve the error message about too many arguments
The location of the application, upto the problematic argument, is computed and
used as the location for the main message.
Two sub-messages are added: one for the suggested location of a potential `;`
and the other for highlighting the extra argument.

Before:

    File "./test.ml", line 4, characters 2-13:
    4 |   print_lines (List.map string_of_int [ 1; 2; 3; 4; 5 ])
          ^^^^^^^^^^^
    Error: This function has type string list -> unit
           It is applied to too many arguments; maybe you forgot a `;'.

After:

    File "./test.ml", lines 4-5, characters 2-15:
    4 | ..print_lines (List.map string_of_int [ 1; 2; 3; 4; 5 ])
    5 |   print_endline......
    Error: This function has type string list -> unit
           It is applied to too many arguments
    File "./test.ml", line 4, characters 56-57:
     |   print_lines (List.map string_of_int [ 1; 2; 3; 4; 5 ])
                                                               ^
      Maybe you forgot a ';'.
    File "./test.ml", line 5, characters 2-15:
    5 |   print_endline "foo"
          ^^^^^^^^^^^^^
      This argument is not expected.