Misc.fatal_error: use Format.eprintf instead of prerr_string
The use of a non-Format output caused troubles when called from the
toplevel. In comparison, Misc.fatal_errorf was already using Format,
and many files freely mix those two functions.

The suggestion comes from Florian Angeletti in #1918.

Reviewed by: ?

(no change entry needed)