Print short expressions in type error messages
Re-use the mechanism implemented for the "This function" message for
type clash errors.

Type error messages now look like this:

    Error: The expression '43' has type int
           but an expression was expected of type int32

The type of `Pattern_type_clash` changed for consistency, but this is
not required.