Add BigArray.Genarray.free
Free the memory used by a bigarray, setting all dimensions to zero to
prevent further use.

This is useful to ensure that memory-mapped files are closed promptly,
without waiting for the garbage collector. Otherwise, mapping a large
number of files may hit operating system limits on the number of open
files.

If e.g. [sub_left] is used to create multiple bigarrays backed by the
same memory block, [free] must be called on all of them before the
memory is actually released.

Test program:

(* ocamlc unix.cma bigarray.cma test.ml -o test && ./test *)

open Bigarray

let maps = ref []

let open_and_close () =
  let fd = Unix.(openfile "/etc/passwd" [O_RDONLY; O_NONBLOCK] 0o644) in
  let mapped = Array1.map_file fd char c_layout false 100 in
  (* Make bug more obvious by ensuring no GC *)
  maps := mapped :: !maps;
  (* Array1.free mapped; *)
  Unix.close fd

let () =
  let i = ref 0 in
  while true do
    incr i;
    open_and_close ();
    Printf.printf "Mapped %d files\n%!" !i
  done

...
Mapped 35589 files
Mapped 35590 files
Fatal error: exception Unix.Unix_error(Unix.ENFILE, "open", "/etc/passwd")