PR 10661: known-bad test
Weirdly enough, this example behaves differently depending on whether the repro case is passed as a relative or absolute path.

```
$ ROOT=../../.. ; $ROOT/runtime/ocamlrun $ROOT/ocamlc -nostdlib -I $ROOT/stdlib -c ./pr10661_bad.ml
Fatal error: exception File "typing/signature_group.ml", line 52, characters 19-25: Assertion failed

$ ROOT=../../.. ; $ROOT/runtime/ocamlrun $ROOT/ocamlc -nostdlib -I $ROOT/stdlib -c $(pwd)/pr10661_bad.ml
File "/home/gasche/Prog/ocaml/github-4.13/testsuite/tests/typing-modules-bugs/pr10661_bad.ml", line 1:
Error: The implementation /home/gasche/Prog/ocaml/github-4.13/testsuite/tests/typing-modules-bugs/pr10661_bad.ml
       does not match the interface (inferred signature):  ... In module M:
       The type `#row' is required but not provided
       File "/home/gasche/Prog/ocaml/github-4.13/testsuite/tests/typing-modules-bugs/pr10661_bad.ml", lines 9-10, characters 2-5:
         Expected declaration
```